"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class heartbeat_message(object):
    __slots__ = ["timestamp", "mode", "botUID", "isMoving", "apply_brakes"]

    __typenames__ = ["int64_t", "int8_t", "int8_t", "boolean", "boolean"]

    __dimensions__ = [None, None, None, None, None]

    def __init__(self):
        self.timestamp = 0
        self.mode = 0
        self.botUID = 0
        self.isMoving = False
        self.apply_brakes = False

    def encode(self):
        buf = BytesIO()
        buf.write(heartbeat_message._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qbbbb", self.timestamp, self.mode, self.botUID, self.isMoving, self.apply_brakes))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != heartbeat_message._get_packed_fingerprint():
            raise ValueError("Decode error")
        return heartbeat_message._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = heartbeat_message()
        self.timestamp, self.mode, self.botUID = struct.unpack(">qbb", buf.read(10))
        self.isMoving = bool(struct.unpack('b', buf.read(1))[0])
        self.apply_brakes = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if heartbeat_message in parents: return 0
        tmphash = (0x62dd65b5a8996ef4) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if heartbeat_message._packed_fingerprint is None:
            heartbeat_message._packed_fingerprint = struct.pack(">Q", heartbeat_message._get_hash_recursive([]))
        return heartbeat_message._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

