"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class heartbeat(object):
    __slots__ = ["timestamp", "status", "isMoving"]

    __typenames__ = ["int64_t", "int8_t", "boolean"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.timestamp = 0
        self.status = 0
        self.isMoving = False

    def encode(self):
        buf = BytesIO()
        buf.write(heartbeat._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qbb", self.timestamp, self.status, self.isMoving))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != heartbeat._get_packed_fingerprint():
            raise ValueError("Decode error")
        return heartbeat._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = heartbeat()
        self.timestamp, self.status = struct.unpack(">qb", buf.read(9))
        self.isMoving = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if heartbeat in parents: return 0
        tmphash = (0x848c92dc9703ba34) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if heartbeat._packed_fingerprint is None:
            heartbeat._packed_fingerprint = struct.pack(">Q", heartbeat._get_hash_recursive([]))
        return heartbeat._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

